Database branch
j-sunaga/task-app pull request #1
Opened 2020-03-27 07:52 UTC by j-sunaga

STEP1. TaskモデルのCRUD機能 + テスト（システムスペック）を作成しました。

2020-03-29 03:40 UTC, j-sunaga commented
１.テストコード、２.ユーザ入力欄、３.taskテーブルのコラム名の修正を行いました。

2020-03-29 06:17 UTC, yuji91 requested changes
確認しました。以下の指摘事項について対応をお願いします。

2020-03-29 06:17 UTC, yuji91 commented on app/assets/javascripts/tasks.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
必要ないファイルは削除をお願いします！

2020-03-29 06:17 UTC, yuji91 commented on app/assets/stylesheets/tasks.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
こちらのファイルも必要ないかと思われます。

2020-03-29 06:17 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +  end
`rails generate`で作成されるコメントは不要であれば削除をお願いします。

2020-03-29 06:17 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +  end
`render :edit`するだけで中身のないメソッドは`def edit; end`と1行で記載できます。
この記載の方が、アクションメソッド内の記述の記載漏れがないということが明示できるので良いかと思います。

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/SingleLineMethods
Rubocopの設定でも`AllowIfMethodIsEmpty: true (default)`とデフォルトでこの規約が設定されます。

2020-03-29 06:17 UTC, yuji91 commented on app/helpers/tasks_helper.rb
> +end
このファイルが存在すると`Task`に関連するHelplerメソッドが定義されているかという誤解を産みます。
メソッドがない場合は空ファイルを残さず削除した方が良いと思います。

2020-03-29 06:17 UTC, yuji91 commented on app/models/task.rb
> +  belongs_to :user,optional: true
細かいですが`optional`の前にスペースがないので追加をお願いします。

2020-03-29 06:17 UTC, yuji91 commented on app/models/user.rb
> +end
ValidationやAssociationの定義はこの時点で設定しなくても大丈夫でしょうか？

2020-03-29 06:17 UTC, yuji91 commented on db/migrate/20200329032454_rename_task_name_column_to_tasks.rb
> +end
`merge`していない同一のPullRequest内であれば他の開発者に影響がないので、最初に作成したmigrationファイルを直接修正してしまって大丈夫です。

2020-03-29 06:17 UTC, yuji91 commented on test/controllers/tasks_controller_test.rb
> +class TasksControllerTest < ActionDispatch::IntegrationTest
SystemSpecが記載されていればControllerSpecを作成する必要は特にないかと思いますが、いかがでしょうか？
(ControllerSpecで確認する内容をSystemSpecのテストケースで網羅しているため)

2020-03-29 06:17 UTC, yuji91 commented on test/fixtures/tasks.yml
> +  deadline: 2020-03-21
`2020-03-21`に何か意図がなければ、ランダムな値を設定した方が良いです。

2020-03-29 06:17 UTC, yuji91 commented on test/fixtures/users.yml
> +  email: MyString
emailにMyStringという文字列を登録するのはテストデータとして不適切です。
`@example.com`という存在しないことが保証されているドメインを利用したテストデータを登録してください。

2020-03-29 06:17 UTC, yuji91 commented on test/models/task_test.rb
> +end
テストケースの中身のないテストファイルは残したままにせず、削除してください。
「modelのテストが用意されている」という誤解を産みます。

2020-03-29 06:17 UTC, yuji91 commented on test/system/tasks_test.rb
> +end
`RSpec`でのテストが記載されていれば`minitest`は作成必要ないかと思いますが、残しておきたければこのままでも大丈夫です！

2020-03-29 08:18 UTC, j-sunaga commented on app/assets/javascripts/tasks.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
削除しました。ご確認願います。

2020-03-29 08:18 UTC, j-sunaga commented on app/assets/stylesheets/tasks.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
削除しました。ご確認願います。

2020-03-29 08:18 UTC, j-sunaga commented on app/controllers/tasks_controller.rb
> +  end
削除しました。ご確認願います。

2020-03-29 08:18 UTC, j-sunaga commented on app/controllers/tasks_controller.rb
> +  end
変更しました。ご確認願います。

2020-03-29 08:18 UTC, j-sunaga commented on app/helpers/tasks_helper.rb
> +end
削除しました。ご確認願います。

2020-03-29 08:19 UTC, j-sunaga commented on test/controllers/tasks_controller_test.rb
> +class TasksControllerTest < ActionDispatch::IntegrationTest
controller specを削除しました。ご確認願います。

2020-03-29 08:19 UTC, j-sunaga commented on test/fixtures/tasks.yml
> +  deadline: 2020-03-21
ランダムな値を設定しました。

2020-03-29 08:19 UTC, j-sunaga commented on test/fixtures/users.yml
> +  email: MyString
@exampleに変更しました。

2020-03-29 08:19 UTC, j-sunaga commented on test/models/task_test.rb
> +end
削除しました。ご確認願います。

2020-03-29 08:19 UTC, j-sunaga commented on test/system/tasks_test.rb
> +end
削除しました。ご確認願います。

2020-03-29 08:34 UTC, yuji91 commented on spec/system/task_spec.rb
> +require 'rails_helper'
requireの後は1行開けるのが慣例です。

2020-03-29 08:36 UTC, yuji91 commented on spec/system/task_spec.rb
> +       task = FactoryBot.create(:task, name: 'task')
https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#configure-your-test-suite

rails_helper や spec_helper のconfigに追記することで`FactoryBot.`という記載は省略することが可能です。

2020-03-29 08:37 UTC, yuji91 commented on test/fixtures/users.yml
> +  email: "@example.com"
ドメインしか記載されていないので、メールアドレスのデータとして適切な形になる様に`test01`などの文言を付与してください。

2020-03-29 08:39 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = FactoryBot.create(:task, name: 'task')
`name`をFactoryBotの値から変更する必要はありますか？
また`let(:task) { FactoryBot.create(:task, name: 'task') }`を先に定義すると、ここのtaskローカル変数への代入を省略できます。

2020-03-29 08:41 UTC, yuji91 commented on spec/factories/tasks.rb
> +    deadline { Random.rand(Date.parse("2020/01/01") .. Date.parse("2020/03/30")) }
`2020/1/1~2020/3/30`を指定する特定の意味がなければ、`1.month.ago`の様な形式が良いかと思います。

2020-03-29 08:41 UTC, yuji91 commented on spec/factories/tasks.rb
> +    priority { 'test_priority' }
statusやpriorityはenumで定義されていると思うので、Stringの文字列を定義するのはテストデータとして不適切だと思います。

2020-03-29 08:42 UTC, yuji91 requested changes
追加でコメントしました。

2020-03-29 09:08 UTC, j-sunaga commented on spec/system/task_spec.rb
> +require 'rails_helper'
e2c7a72で修正しました。

2020-03-29 09:08 UTC, j-sunaga commented on app/helpers/tasks_helper.rb
> +end
b7323c8で削除

2020-03-29 09:09 UTC, j-sunaga commented on app/assets/javascripts/tasks.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
b7323c8で削除

2020-03-29 09:09 UTC, j-sunaga commented on app/assets/stylesheets/tasks.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
b7323c8で削除

2020-03-29 09:10 UTC, j-sunaga commented on app/controllers/tasks_controller.rb
> +  end
c7f6071で削除

2020-03-29 09:10 UTC, j-sunaga commented on app/controllers/tasks_controller.rb
> +  end
ee8fabbで修正

2020-03-29 09:11 UTC, j-sunaga commented on app/helpers/tasks_helper.rb
> +end
a2bf5a6で削除

2020-03-29 09:11 UTC, j-sunaga commented on test/controllers/tasks_controller_test.rb
> +class TasksControllerTest < ActionDispatch::IntegrationTest
20368edで削除

2020-03-29 09:12 UTC, j-sunaga commented on test/fixtures/tasks.yml
> +  deadline: 2020-03-21
e61f925にて修正

2020-03-29 09:12 UTC, j-sunaga commented on test/fixtures/users.yml
> +  email: MyString
9a7f59cにて修正

2020-03-29 09:13 UTC, j-sunaga commented on test/models/task_test.rb
> +end
8cf649bにて削除

2020-03-29 09:13 UTC, j-sunaga commented on test/system/tasks_test.rb
> +end
4a67247にて削除

2020-03-29 09:20 UTC, j-sunaga commented on spec/system/task_spec.rb
> +       task = FactoryBot.create(:task, name: 'task')
808ffbbにて修正

2020-03-29 09:22 UTC, j-sunaga commented on test/fixtures/users.yml
> +  email: "@example.com"
d7195e0にて修正

2020-03-29 09:22 UTC, yuji91 requested changes
https://github.com/j-sunaga/task-app/pull/1#discussion_r399763489 などのコミットID以外のコメントについては見辛くなるので削除してしまった方が良いです。

https://github.com/j-sunaga/task-app/pull/1#discussion_r399768751 のIDについては半角スペースを入れることでリンクになり、レビュアーが確認しやすくなります。

2020-03-29 09:50 UTC, j-sunaga commented on spec/system/task_spec.rb
> +        task = FactoryBot.create(:task, name: 'task')
fddd97e FactoryBotの値でテストするように修正
b7373de ローカル変数ではなくletを利用するように修正

2020-03-29 09:53 UTC, j-sunaga commented on spec/factories/tasks.rb
> +    deadline { Random.rand(Date.parse("2020/01/01") .. Date.parse("2020/03/30")) }
f7d7f7f 修正

2020-03-29 10:53 UTC, j-sunaga commented on spec/factories/tasks.rb
> +    priority { 'test_priority' }
a8960f2 修正

2020-03-30 03:04 UTC, merged

2020-03-30 03:04 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +    end
インデント揃えた方が見やすいです。

```ruby
private

def set_task
end
```

2020-03-30 03:06 UTC, yuji91 commented on spec/factories/tasks.rb
> +    priority { 0 }
`0`だと何を指しているかが分からないので`:uncompleted``:low`などのsymbolを設定してください。

2020-03-30 03:07 UTC, yuji91 commented on test/fixtures/tasks.yml
> +  priority: 0
ここもSymbolでお願いします。