ステップ3 基本的な各種設定 + デプロイ
j-sunaga/task-app pull request #3
Opened 2020-04-03 08:02 UTC by j-sunaga

ステップ３を実施しましたのでレビューお願いいたします。

2020-04-04 01:40 UTC, j-sunaga commented
新規タスクで終了期限を登録し、編集画面で見ると終了期限が表示されない

2020-04-04 01:45 UTC, j-sunaga commented
タスク新規登録エラー時に終了期限が消えてしまう

2020-04-04 01:45 UTC, j-sunaga commented
検索キーとなるものについては、インデックス化しましょう
　→　データ数が多くなったときに高速化するためです。

2020-04-04 01:46 UTC, j-sunaga commented
終了期限のソートは、終了期限の近いものから順に並べたほうが良いですね

2020-04-04 02:13 UTC, j-sunaga commented
> 新規タスクで終了期限を登録し、編集画面で見ると終了期限が表示されない

1992060 修正

2020-04-04 02:14 UTC, j-sunaga commented
> タスク新規登録エラー時に終了期限が消えてしまう

1992060 修正

2020-04-04 02:15 UTC, j-sunaga commented
編集画面で優先順位とステータスが初期値に戻ってしまう問題
>5c13c27 修正

2020-04-04 02:20 UTC, j-sunaga commented
> 終了期限のソートは、終了期限の近いものから順に並べたほうが良いですね
f899ce7 修正

2020-04-04 02:28 UTC, j-sunaga commented
> 検索キーとなるものについては、インデックス化しましょう
> 　→　データ数が多くなったときに高速化するためです。

4554fcb 修正

![スクリーンショット 2020-04-04 11 28 02](https://user-images.githubusercontent.com/55880360/78416878-6a93c680-7667-11ea-9f9f-5bde50f38ed3.png)

2020-04-04 02:31 UTC, j-sunaga commented
ステップ3: KaminariというGemを使って一覧画面にページネーションを追加しましょう。

2020-04-04 02:34 UTC, j-sunaga commented
> ステップ3: KaminariというGemを使って一覧画面にページネーションを追加しましょう。

kaminariを追加し、ページネーションを実装しておりますが、いかがでしょうか？

![スクリーンショット 2020-04-04 11 32 19](https://user-images.githubusercontent.com/55880360/78416947-1fc67e80-7668-11ea-8a24-2fb9fb128cdf.png)
![スクリーンショット 2020-04-04 11 32 48](https://user-images.githubusercontent.com/55880360/78416957-294fe680-7668-11ea-8b59-4f7ae278c980.png)

2020-04-04 02:35 UTC, j-sunaga commented
作成日時の降順での並び替えのテストをsystem specまたはfeature specで追記しましょう。

2020-04-04 02:46 UTC, j-sunaga commented
> > 終了期限のソートは、終了期限の近いものから順に並べたほうが良いですね
> > 7b48bde 修正

2020-04-04 03:18 UTC, j-sunaga commented
> 作成日時の降順での並び替えのテストをsystem specまたはfeature specで追記しましょう。

こちらのテストはいかがでしょうか？

![スクリーンショット 2020-04-04 12 18 11](https://user-images.githubusercontent.com/55880360/78417580-63bc8200-766e-11ea-8061-2a9724027628.png)

2020-04-04 04:01 UTC, j-sunaga commented
ステップ3: 【+α要件】さらに自分でCSSやJavaScriptを書いて高度なデザインを付けましょう。

>8cd360a footer追加

2020-04-04 04:02 UTC, j-sunaga commented
【+α要件】自分で調べて、Basic認証を入れてみましょう。

>Herokuにbasic認証を入れていますのでご確認お願い致します。
ID: admin
pass : password

2020-04-04 05:47 UTC, j-sunaga commented
ステップ3: バリデーションにmodelのテストを追加しましょう。
こちら記載されていますでしょうか？modelのテストは、spec/models/task_spec.rbの中に記載します。

2020-04-04 05:48 UTC, j-sunaga commented
ステップ3: ステータスのテストをsystem specまたはfeature specで追記しましょう。
　→　こちら記載されていますでしょうか？

2020-04-04 07:31 UTC, yuji91 requested changes
コメントしました。
RSpecの`Factory`や`let`の使用についてはやや難しいので実装側の指摘が対応できれば保留して進んでしまっても良いかと思います。

2020-04-04 07:31 UTC, yuji91 commented on spec/system/task_spec.rb
> +        create(:second_task, name: "search_title2",detail:'search_title2',status:'working')
テストデータを複数件作成する場合は`create_list`を使うのが一般的です。
`create_list(:task, 2)`という形で作成する数を入力するだけなので管理が楽です。

この際、Factoryの定義では sequence を使って名前が重複しないようにした方が良いです。
(uniqueness: true のバリデーションがあると2件目以降のテストデータ作成で失敗するため)

複数件作成する際のステータスを変えたい場合は、作成時のステータスの値をランダムにしたり、特定のステータスのデータが欲しい場合は別途`trait`という区分を使うのが一般的です。

2020-04-04 07:31 UTC, yuji91 commented on spec/factories/tasks.rb
> +    priority { 'low' }
enumの設定値はシングルクォートで囲ったStringの文字列ではなく`:waiting`などの`Symbol`で記載しましょう。
対象のカラムがStringの文字列ではなく、Integerで宣言された値が入るカラムであることが明示できます。

2020-04-04 07:31 UTC, yuji91 commented on app/models/task.rb
> +  scope :status, -> (query) { where(status: "#{query}") }
enum の status については`Task.waiting`で一覧を取得できるので、この`scope`の記載は不要となります。

2020-04-04 07:31 UTC, yuji91 commented on app/views/layouts/application.html.erb
> +    </nav>
Viewファイルの雛形である application.html.erb にページ固有のHeader情報を直接記載するのは良くないです。
Headerは`部分テンプレート`として呼び出す形式にしましょう。

異なった内容の表示や、ログインの有無によって表示するヘッダーを切り替えるなどの対応が可能となります。

2020-04-04 07:31 UTC, yuji91 commented on app/views/layouts/application.html.erb
> +    </div>
この部分の記載は何を指している部分なのかを読み取りづらいため、
`_error_message.html.erb`などの名前をつけた部分テンプレートを呼び出す形にした方が良いです。

2020-04-04 07:31 UTC, yuji91 commented on app/views/layouts/application.html.erb
> +  </footer>
footerも`部分テンプレート`に切り出して起きましょう。

2020-04-04 07:31 UTC, yuji91 commented on spec/models/task_spec.rb
> +    task = Task.new(detail: "task_detail",deadline: 1.month.ago, status: :waiting, priority: :low)
`FactoryBot`を使っている場合は`build(:task, name: nil)`で記載できます。

2020-04-04 07:31 UTC, yuji91 commented on spec/models/task_spec.rb
> +    # ここに内容を記載する
`# ここに内容を記載する`というコメントは不要になると思います。

2020-04-04 07:31 UTC, yuji91 commented on spec/models/task_spec.rb
> +      expect(Task.name_like('scope1').count).to eq 1
`1件取得できること`をテストするのではなく`該当するデータが取得でき、該当しないデータは取得できないこと`をテストするべきだと思います。

2020-04-04 07:31 UTC, yuji91 commented on spec/system/task_spec.rb
> +    @task2=create(:second_task)
インスタンス変数で作成するよりは`let(:task) { create(:task} )`で`task`と記載すれば`FactoryBot.create(:task)`が実行されるように宣言した方が良いです。
対象のデータが作成済である状態にしたい場合は`let!(:task) { create(:task} )`と記載すると遅延評価されずに即時実行されます。
複数件作成したい場合は`let(:tasks) { create_list(:task) }`を使うと良いと思います。

2020-04-04 07:31 UTC, yuji91 commented on spec/system/task_spec.rb
> +        old_task = create(:task, name: 'old_task',detail: 'old_task',deadline: 3.month.ago)
new, oldとここで宣言しても良いですが「過去に作成して完了済である」という意図の`completed`などの`trait`をFactoryBot側で定義して`create(:task, :completed)`で古い日付のデータを作成し、新しい日付データは通常の`create(:task)`で作成したものを使うようにすると作成するテストデータの汎用性が上がります。

2020-04-04 07:31 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +    end
indexアクションが肥大化しているFatControllerのパターンとなります。
このアクションは`@tasks`というリソースを取得して`render :index`でレスポンスを返すという役割に集中して「検索時のロジック、パターンが何か」という部分については責務がないので知る必要がありません。

`@tasks = Task.search`のように検索結果を取得するという記載だけ残し、Modelクラスに`self.search`とクラスメソッドを作成してロジックを委譲しましょう。引数が必要であれば適宜渡してください。

このようにメソッドを呼び出す形にすることで責務が単純になり、メンテナンス性が向上します。
`カプセル化`という概念なので調べてみてください。

2020-04-04 07:31 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +    if params[:search].present? then
Rubyでは`then`は通常記載しないのが一般的かと思われます。

2020-04-04 08:21 UTC, j-sunaga commented on spec/factories/tasks.rb
> +    priority { 'low' }
959cdec 修正

2020-04-04 08:50 UTC, j-sunaga commented on app/models/task.rb
> +  scope :status, -> (query) { where(status: "#{query}") }
09116d4 修正

2020-04-04 09:13 UTC, j-sunaga commented on app/views/layouts/application.html.erb
> +    </nav>
94c7483 修正

2020-04-04 09:20 UTC, j-sunaga commented on app/views/layouts/application.html.erb
> +    </div>
2d75c23 noticeを部分テンプレート

2020-04-04 09:21 UTC, j-sunaga commented on app/views/layouts/application.html.erb
> +  </footer>
94c7483 修正

2020-04-05 03:55 UTC, j-sunaga commented on app/controllers/tasks_controller.rb
> +    if params[:search].present? then
0f88e25 修正

2020-04-05 04:23 UTC, yuji91 commented
コミットIDにリンクがあるものとないものがあるようです。
コミットIDはリモートのブランチにpushした後に記載するのが望ましいです。
(リンクとして機能しないため、修正箇所を確認できないため)

慣れないと思うのですべて修正しきる必要はないですが、なるべくこのPullRequest内に存在するコミットのIDをリンクとして記載するようにしてください。

2020-04-05 04:31 UTC, j-sunaga commented on spec/models/task_spec.rb
> +      expect(Task.name_like('scope1').count).to eq 1
51eb981 修正

2020-04-05 06:20 UTC, j-sunaga commented on spec/system/task_spec.rb
> +        create(:second_task, name: "search_title2",detail:'search_title2',status:'working')
c59aec4 FactoryBotの修正
20e97ba systemテストの修正

2020-04-05 06:21 UTC, j-sunaga commented on spec/system/task_spec.rb
> +    @task2=create(:second_task)
20e97ba systemテストの修正

2020-04-05 06:21 UTC, j-sunaga commented on spec/system/task_spec.rb
> +        old_task = create(:task, name: 'old_task',detail: 'old_task',deadline: 3.month.ago)
20e97ba systemテストの修正

2020-04-05 06:41 UTC, yuji91 commented on app/models/task.rb
> +  scope :status, -> (query) { where(status: "#{query}") }
こちらの修正について問題点があったのでコメントしました。
該当のコードは既に修正されているようなので対応不要となりますが、下記の内容だけ確認をお願いします。
https://github.com/j-sunaga/task-app/commit/09116d4b0f8bd58f0e7ba0a087d2262c41fa28d9#r38295472

2020-04-05 06:44 UTC, yuji91 commented on app/views/layouts/application.html.erb
> +    </nav>
コミットIDのリンクが確認できませんでした。

2020-04-05 06:44 UTC, yuji91 commented on app/views/layouts/application.html.erb
> +    </div>
コミットIDのリンクが確認できませんでした。

2020-04-05 06:47 UTC, yuji91 commented on app/views/layouts/application.html.erb
> +  </footer>
こちら修正に問題があったのでコメントしました。
https://github.com/j-sunaga/task-app/commit/94c7483a8eddd059c0d2a7f29da9874708176645#commitcomment-38295521

2020-04-05 06:54 UTC, yuji91 commented on spec/factories/tasks.rb
> +    priority { 'low' }
コミットIDのリンクが確認できませんでした。

2020-04-05 07:10 UTC, yuji91 requested changes
こちら確認してコメントしました。

2020-04-05 07:10 UTC, yuji91 commented on spec/system/task_spec.rb
> +        create_list(:task, 2, :task_list)
create_list形式でFactoryBotのcreateを宣言するとtaskは繰り返し作成されるので`task_list`というtraitの指定は不要となります。

2020-04-05 07:10 UTC, yuji91 commented on spec/factories/tasks.rb
> +      sequence :name do |n|
こちらの`sequence`は元々の`factory :task`の`name`に記載しましょう。
list形式で複数件Factoryのデータを作成するかどうかは`trait`ではなくSpecファイル側での指定によって制御するので、
この`task_list`という`trait`は不要となります。

2020-04-05 07:10 UTC, yuji91 commented on spec/factories/tasks.rb
> +    trait :high_priority do
`priority`がhighである状態を作りたいだけであれば、traitとして用意するまでもなく
`let(:high_priority_task) { create(:task, status: :high) }`と記載するだけで十分だと思います。

他のカラム内容もまとめて指定したい場合や、AdminUserなど頻繁に使用する別ステータスのデータであれば`trait`でどのような状態かを定義しておきますが、今回の場合は作らなくても良いかと思います。

同様に`low_priority`や`middle_priority`などenumのステータス毎に他の`trait`も用意するとキリがないので。

2020-04-05 07:10 UTC, yuji91 commented on spec/factories/tasks.rb
> +    trait :old_task do
`trait`でtaskと言う文字列を含めなくても、呼び出し側で`let(:old_task) { create(:task, :old)}`と記載できるので状態を表す単語だけ`trait`に記載するだけで良いと思います。

2020-04-05 07:10 UTC, yuji91 commented on spec/factories/tasks.rb
> +    name { 'task' }
こちらのnameに`sequence`を定義しておきましょう。
`uniqueness: true`が設定されていた場合複数回`create(:task)`を実行されるとバリデーションエラーで失敗します。

2020-04-05 07:10 UTC, yuji91 commented on config/locales/kaminari.ja.yml
> +      truncate: ""
こちら対応途中または次回Stepで対応であれば`# TODO: 次回Stepで対応`のようなコメントがあると確認しやすいです。

2020-04-05 07:10 UTC, yuji91 commented on app/views/tasks/show.html.erb
> +<%= render 'layouts/header' %>
各viewファイルにheaderとfooterを呼び出す処理を記載するとメンテナンスが大変になります。
どこで何を読んでいるかをそれぞれ確認しないといけないです。

全体のviewファイルの雛形である`application.html.erb`でheader, footerのレイアウトを呼び出すようにしてください。

2020-04-05 07:11 UTC, yuji91 commented on spec/system/task_spec.rb
> +        create(:second_task, name: "search_title2",detail:'search_title2',status:'working')
下記のコメントを確認してください。
https://github.com/j-sunaga/task-app/pull/3#discussion_r403658713

2020-04-05 07:14 UTC, yuji91 requested changes
下記の指摘についてもご対応お願いします。修正が難しいようであれば保留して先に進んでください。
https://github.com/j-sunaga/task-app/pull/3#discussion_r403437825

2020-04-05 07:28 UTC, j-sunaga commented on app/views/tasks/show.html.erb
> +<%= render 'layouts/header' %>
b03ee78 修正

2020-04-05 07:29 UTC, j-sunaga commented on config/locales/kaminari.ja.yml
> +      truncate: ""
こちらはlast, next,previous,truncateという文字を画面上に表示させたくないため、添付のように書いております。

2020-04-05 08:11 UTC, j-sunaga commented on app/views/layouts/application.html.erb
> +    </div>
2d75c23 notice部分テンプレート(再投稿)

2020-04-05 08:11 UTC, j-sunaga commented on app/views/layouts/application.html.erb
> +    </nav>
94c7483 修正(再投稿)

2020-04-05 08:13 UTC, j-sunaga commented on spec/system/task_spec.rb
> +        create_list(:task, 2, :task_list)
4526a49　sequenceのtrait削除

2020-04-05 08:14 UTC, j-sunaga commented on spec/factories/tasks.rb
> +      sequence :name do |n|
4526a49　sequenceのtrait削除

2020-04-05 08:14 UTC, j-sunaga commented on spec/factories/tasks.rb
> +    trait :high_priority do
4526a49　high_priorityのtrait削除

2020-04-05 08:21 UTC, j-sunaga commented on spec/factories/tasks.rb
> +    trait :old_task do
let(:old_task){create(:task,:old)}の処理は以下でよろしいでしょうか？
@old_task = FactoryBot.create(:task,:old)

この場合、'':old trait''ではtask_nameのオーバーライド定義がないため、@old_taskのタスク名は:taskを引き継いでtask_1となり、以下の検証ができないです。
''expect(task_list[0]).to have_content 'old_task'''

let(:old_task)を使ってどのようにtask.nameにold_taskを代入すれば良いでしょうか？

2020-04-05 08:24 UTC, j-sunaga commented on spec/factories/tasks.rb
> +    name { 'task' }
4526a49 修正

2020-04-05 08:50 UTC, j-sunaga commented on app/controllers/tasks_controller.rb
> +    end
2223535 修正

2020-04-05 08:51 UTC, j-sunaga commented on spec/factories/tasks.rb
> +    priority { 'low' }
959cdec 修正(リンク無効のため再投稿)

2020-04-05 08:52 UTC, j-sunaga commented on spec/factories/tasks.rb
> +    priority { 'low' }
959cdec 修正(リンク無効のため再投稿)

2020-04-06 03:56 UTC, yuji91 commented on spec/factories/tasks.rb
> +    trait :old_task do
> let(:old_task){create(:task,:old)}の処理は以下でよろしいでしょうか？

`old_task = FactoryBot.create(:task,:old)` となり、インスタンス変数ではなくローカル変数として扱います。また、DB側の情報が更新された場合は`old_task.reload`と更新すると反映されます。

2020-04-06 03:57 UTC, yuji91 commented on spec/factories/tasks.rb
> +    trait :old_task do
> let(:old_task)を使ってどのようにtask.nameにold_taskを代入すれば良いでしょうか？

`let(:old_task){create(:task,:old, name: 'old_task')}`などのように`name`を個別指定すれば良いと思います。

2020-04-06 03:59 UTC, yuji91 commented
質問に回答しました。
https://github.com/j-sunaga/task-app/pull/3#discussion_r403817321
https://github.com/j-sunaga/task-app/pull/3#discussion_r403817547

2020-04-06 04:01 UTC, yuji91 commented
こちらも対応をお願いします。
https://github.com/j-sunaga/task-app/pull/3/files#r403436664

2020-04-06 10:15 UTC, j-sunaga commented on spec/factories/tasks.rb
> +    trait :old_task do
40da0f7 修正

2020-04-06 11:29 UTC, j-sunaga commented
> こちらも対応をお願いします。
> https://github.com/j-sunaga/task-app/pull/3/files#r403436664

39d15f6 修正

2020-04-07 01:55 UTC, yuji91 approved these changes
修正確認しました。
2点追加で指摘しましたが、要件の合格判定が出ているので次のステップのPRで修正しても大丈夫です。

2020-04-07 01:55 UTC, yuji91 commented on spec/factories/tasks.rb
> +    trait :old_task do
traitの状態名に`_task`という文字は不要ですね。
`let(:old_task){create(:task,:old_task, name: 'old_task')}`
`let(:old_task){create(:task,:old, name: 'old_task')}`

2020-04-07 01:55 UTC, yuji91 commented on app/views/tasks/index.html.erb
> +      <% end %>
このtaskをeachしている部分を`_task.html.erb`と部分テンプレートに切り出すと
`<%= render @tasks %>`の1行のみで記載することが可能で、こちらの方が件数表示時のパフォーマンスが良いです。

2020-04-07 02:28 UTC, j-sunaga reviewed
> 修正確認しました。
> 2点追加で指摘しましたが、要件の合格判定が出ているので次のステップのPRで修正しても大丈夫です。

下記、２点修正しました。次のステップに進みます。

1f616df task.eachの部分テンプレート修正
9c03c66 traitの:old_taskを:oldに修正

2020-04-07 02:28 UTC, j-sunaga commented on spec/models/task_spec.rb
> +    task = Task.new(detail: "task_detail",deadline: 1.month.ago, status: :waiting, priority: :low)
39d15f6 修正

2020-04-07 02:30 UTC, merged

2020-04-07 09:31 UTC, yuji91 commented on app/views/tasks/index.html.erb
> +    <%= render 'layouts/task', collection: @tasks %>
taskの部分テンプレートを`app/views/task/_task.html.erb`として配置すると`<%= render @tasks %>`と記載することが可能です！