STEP5 エラーページ + ラベリング機能
j-sunaga/task-app pull request #5
Opened 2020-04-16 04:42 UTC by j-sunaga

2020-04-18 04:51 UTC, yuji91 requested changes
コーディングレベルでのフィードバックを行いました。

2020-04-18 04:51 UTC, yuji91 commented on app/controllers/labels_controller.rb
> +    if current_user.labels.find_by(name:label_params[:name]).blank?
モデルのValidationのカスタムメソッドを使うとif文のネストが解消できます。
https://railsguides.jp/active_record_validations.html#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89

2020-04-18 04:51 UTC, yuji91 commented on app/controllers/labels_controller.rb
> +    if current_user.labels.where.not(id:@label.id).find_by(name:label_params[:name]).blank?
この部分もカスタムメソッドに責務を寄せた方が良いです。
https://railsguides.jp/active_record_validations.html#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89

2020-04-18 04:51 UTC, yuji91 commented on app/controllers/labels_controller.rb
> +    @label.destroy
もし削除処理が失敗した場合にエラーとして検知できるよう`destroy!`と破壊的メソッドにしておいても良いかと思います。

2020-04-18 04:51 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +    end
`@task.labels.delete_all unless params[:task][:label_ids]`と後置ifを使うことで1行で記載できますが、
この部分はどのような意図で記載されたコードなのか分かりにくいため、下記のように別で定義したメソッドを呼び出す形にした方が分かりやすくなると思います。メソッド名は処理の意図によって適宜変えてください。
```ruby
clear_label if xxx

def xxx
  @task.labels_delete_all
end
```

2020-04-18 04:51 UTC, yuji91 commented on app/models/task.rb
> +        end
インデントは揃えた方が見やすいです。

2020-04-18 04:51 UTC, yuji91 commented on app/views/labels/index.html.erb
> +      <% @labels.each do |label| %>
`app/views/labels/_label.html.erb`の部分テンプレートを呼び出す形で記載すると、
`<%= render @labels %>`の形式で記載できます。
件数が100件近くあると分かりますが、こちらの記載の方が実行時のSQLの負荷が少ないです。

2020-04-18 04:51 UTC, yuji91 commented on db/seeds.rb
> +      email: "admin_#{n + 1}@test.com",
`@test.com`というドメインはおそらく実在するので、実在しない`@example.com`を使いましょう。

2020-04-18 04:51 UTC, yuji91 commented on spec/models/label_spec.rb
> +    expect(label).not_to be_valid
`to be_invalid`という形でも記載できますが、好みなのでどちらでも大丈夫です。

2020-04-18 10:06 UTC, j-sunaga commented on app/models/task.rb
> +        end
f7b1197 修正

2020-04-18 10:06 UTC, j-sunaga commented on app/controllers/labels_controller.rb
> +    @label.destroy
bd3ea5f 修正

2020-04-18 10:09 UTC, j-sunaga commented on app/views/labels/index.html.erb
> +      <% @labels.each do |label| %>
1b1ef41 修正

<% render @labels %>にするとデータが複数回繰り替えされて表示されてしまうため
<% render 'label', collection: @labels %>にしております。

![image](https://user-images.githubusercontent.com/55880360/79634842-0d8c2a80-81a8-11ea-9108-a5ddded64c2b.png)

2020-04-18 10:09 UTC, j-sunaga commented on db/seeds.rb
> +      email: "admin_#{n + 1}@test.com",
9483573 修正

2020-04-18 10:09 UTC, j-sunaga commented on spec/models/label_spec.rb
> +    expect(label).not_to be_valid
修正 2002843

2020-04-18 10:10 UTC, j-sunaga commented on app/controllers/tasks_controller.rb
> +    end
2c3dc39 修正

2020-04-18 10:28 UTC, j-sunaga commented on app/controllers/labels_controller.rb
> +    if current_user.labels.find_by(name:label_params[:name]).blank?
カスタムメソッドですが、バリデーション対象の:nameカラムに条件をつけて検証できるようですが、current_user.labelsと保存対象の@label.nameを比較したいです。
validationにカラム以外の引数を持たせるもしくは他の方法をご存知でしょうか？

実装したいイメージ
```
class Label < ApplicationRecord  
  validate :cannot_save_same_label

  def cannot_save_same_label(current_user.labels)
     if current_users.labels.find_by(name: name).present?
       errors.add(:name, "同じ名前のラベルを保存することはできません")
     end
  end
end
```

2020-04-19 04:44 UTC, yuji91 requested changes
一旦`validationにカラム以外の引数を持たせるもしくは他の方法`以外の部分について確認しました。

2020-04-19 04:44 UTC, yuji91 commented on app/controllers/labels_controller.rb
> +
不要な改行は消しておきましょう。

ちなみに、このようなコードフォーマットの修正は`gem rubocop`を導入して`rubocop -a`コマンドを実行することで自動で修正できることは知っておいてください。

2020-04-19 04:44 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +      @tasks = current_user.labels.find_by(name:params[:label]).tasks
`name: params[:label]`とスペースを空けないと引数の情報が見辛くなってしまいます。

2020-04-19 04:44 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +    @task.labels.delete_all
`delete_all`と`destroy_all`の使い分けは意識してください。

現状だと削除処理を実行した際にActiveRecordのValidationチェックが行われずに直接SQLを実行してしまいます。
意図して行なっているものでない場合は、Validationを介するようにしましょう。

2020-04-19 04:44 UTC, yuji91 commented on app/models/labeling.rb
> +
`#association`という定義をつけるか付けないかは統一した方が良いです。
自分は特段付けなくても良いと思っています。また、不要な行も消しておきましょう。

2020-04-19 04:44 UTC, yuji91 commented on app/models/task.rb
> +
search部分が同じ処理の場合、下記の方が意図が伝わりやすいです。三項演算子を使っても良いかもしれません。


```suggestion
tasks = if xxx
         else
         end
search(tasks, xxx)
```

2020-04-19 04:44 UTC, yuji91 commented on app/views/labels/_label.html.erb
> +  <% @labels.each do |label| %>
部分テンプレートでインスタンス変数を使うとそのテンプレートを呼び出すControllerのアクションで必ず@labelsを定義しなければならないので密結合になります。ローカル変数を呼び出し元のViewから渡して、それを参照する形が良いと思います。

またlabel単体を表す部分テンプレートの内部で @labels.each を記載してloop処理を行うのは、eachしているということがファイル内部を確認しないと分からないため扱いづらくなります。

呼び出し元のViewファイルでループ処理を記載して、部分テンプレートは単体の内容を持つだけに留めておきましょう。

2020-04-19 04:44 UTC, yuji91 commented on app/views/labels/edit.html.erb
> +
先頭に不要な改行があります。

2020-04-19 04:44 UTC, yuji91 commented on db/migrate/20200415043206_create_labels.rb
> +      t.string :name
labelの名前は必須Validationが設定されていると思うので、DBレベルでも必須の制約をかけておきましょう。
現状では直接SQLを実行するとModelで禁止している形式のデータが作成できてしまいます。

2020-04-19 07:52 UTC, j-sunaga commented on app/controllers/labels_controller.rb
> +
e3a7dcb 修正

2020-04-19 07:52 UTC, j-sunaga commented on app/controllers/tasks_controller.rb
> +      @tasks = current_user.labels.find_by(name:params[:label]).tasks
e3a7dcb 修正

2020-04-19 07:52 UTC, j-sunaga commented on app/controllers/tasks_controller.rb
> +    @task.labels.delete_all
e0d9124 修正

2020-04-19 07:53 UTC, j-sunaga commented on app/models/labeling.rb
> +
e3a7dcb 修正

2020-04-19 07:53 UTC, j-sunaga commented on app/models/task.rb
> +
0d21098 修正

2020-04-19 07:54 UTC, j-sunaga commented on app/views/labels/_label.html.erb
> +  <% @labels.each do |label| %>
eecb22f 修正

2020-04-19 07:54 UTC, j-sunaga commented on app/views/labels/edit.html.erb
> +
e3a7dcb 修正

2020-04-19 07:55 UTC, j-sunaga commented on db/migrate/20200415043206_create_labels.rb
> +      t.string :name
b509c66 修正

2020-04-19 08:47 UTC, yuji91 requested changes
確認してコメントしました。

2020-04-19 08:47 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +  def delete_label
すべてのlabelに対してdestroy_allを実行するメソッドなので名前は`destroy_all_labels`などが適切かと思います。
`delete`というメソッド名だと内部ではdestroyではなくdeleteを実行するかのように思えます。

2020-04-19 08:47 UTC, yuji91 commented on app/models/task.rb
> +    input_label.present? ? tasks = current_user.labels.find_by(name: input_label).tasks : tasks = current_user.tasks
`tasks = input_label.present? ? A : B` の形の方が分かりやすいと思います。

2020-04-19 08:47 UTC, yuji91 commented on app/models/user.rb
> +      throw(:abort) if admin == true
`== true`は`present?`で代用できます。

2020-04-19 08:47 UTC, yuji91 commented on app/views/labels/index.html.erb
> +      <% end %>
labelの部分テンプレートを単体で呼び出す形式に変更したので、each文を記載しなくても下記の形で記載できると思います。
```suggestion
      <%= render @labels %>
```

2020-04-24 07:56 UTC, j-sunaga commented on app/controllers/tasks_controller.rb
> +  def delete_label
a230029 修正

2020-04-24 07:56 UTC, j-sunaga commented on app/models/task.rb
> +    input_label.present? ? tasks = current_user.labels.find_by(name: input_label).tasks : tasks = current_user.tasks
dec7eb0 修正

2020-04-24 07:56 UTC, j-sunaga commented on app/models/user.rb
> +      throw(:abort) if admin == true
ab4c07b 修正

2020-04-24 07:57 UTC, j-sunaga commented on app/views/labels/index.html.erb
> +      <% end %>
d35d7e2 修正

2020-04-24 07:58 UTC, j-sunaga commented on app/controllers/labels_controller.rb
> +    if current_user.labels.find_by(name:label_params[:name]).blank?
b14cc41 修正

2020-04-24 07:58 UTC, j-sunaga commented on app/controllers/labels_controller.rb
> +    if current_user.labels.where.not(id:@label.id).find_by(name:label_params[:name]).blank?
b14cc41 修正

2020-04-25 03:29 UTC, merged

2020-04-26 12:55 UTC, yuji91 commented on app/models/label.rb
> +  end
`ユーザ毎に重複した名前のラベルは作成できない`ことがバリデーションの条件だと思うので、カスタムメソッドでなくとも scopeを指定することで対応できることに気づきました。
`validates :name, uniqueness: { scope: :user }`

2020-04-27 04:44 UTC, j-sunaga commented on app/models/label.rb
> +  end
コメントありがとうございます。
おっしゃるとおりuserごとの制約ができました。
https://github.com/j-sunaga/task-app/pull/6